[theme]
# Bleu professionnel pour les boutons et composants actifs
primaryColor = "#004d99"

# Fond blanc pur pour la clarté
backgroundColor = "#ffffff93"

# Gris très clair pour la barre latérale et les zones secondaires
secondaryBackgroundColor = "#f8faf98e"

# Texte sombre (presque noir) pour une lecture parfaite
textColor = "#141518ff"

# Police sans-serif moderne
font = "sans serif"

[server]
# Désactive la barre de menu en haut pour un look plus "App" que "Dashboard"
toolbarMode = "minimal"
