[theme]
# Bleu professionnel pour les boutons et composants actifs
primaryColor = "#004d99"

# Fond blanc pur pour la clarté
backgroundColor = "#ffffff"

# Gris très clair pour la barre latérale et les zones secondaires
secondaryBackgroundColor = "#255dcde9"

# Texte sombre (presque noir) pour une lecture parfaite
textColor = "rgb(2, 5, 15)"

# Police sans-serif moderne
font = "sans serif"

[server]
# Désactive la barre de menu en haut pour un look plus "App" que "Dashboard"
toolbarMode = "minimal"
